project:
  type: website
  output-dir: _site

website:
  title: "Philipp Lutz"
  description: "Political scientist studying migration and European integration."
  site-url: https://philipplutz.github.io/website
  navbar:
    pinned: true  
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
    right:
      - icon: envelope
        href: "mailto:p.lutz@vu.nl"
        aria-label: Email
      - text: "<i class='ai ai-google-scholar'></i>"
        href: "https://scholar.google.com/citations?user=Ml32muAAAAAJ"
      - text: "<i class='ai ai-researchgate'></i>"
        href: "https://www.researchgate.net/profile/Philipp-Lutz-2"
      - text: "<i class='ai ai-orcid'></i>"
        href: "https://orcid.org/0000-0003-2373-0180"
      - text: "<i class='ai ai-bluesky'></i>"
        href: "https://bsky.app/profile/lutzphilipp.bsky.social"
      - icon: linkedin
        href: "https://www.linkedin.com/in/philipp-lutz-78254489"
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
    grid:
      sidebar-width: 200px
      body-width: 800px
      margin-width: 200px
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.5/css/academicons.min.css">
